# Generated by Django 4.2.7 on 2024-05-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_account_currency_deposit_payment_withdraw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
