# Generated by Django 4.2.7 on 2024-05-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='withdraw_bank',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
