# Generated by Django 4.2.7 on 2024-05-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0005_alter_deposit_user_alter_withdraw_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='action',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='Pending', max_length=200, null=True),
        ),
    ]
