# Generated by Django 4.2.7 on 2024-05-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0007_alter_transaction_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='a_type',
            field=models.CharField(choices=[('Forex Trading', 'Forex Trading'), ('Stock Trading', 'Stock Trading'), ('Binary Option Trading', 'Binary Option Trading'), ('NFT/Crypto', 'NFT/Crypto')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
