# Generated by Django 4.2.7 on 2024-05-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0009_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='logo',
            field=models.FileField(null=True, upload_to='qr_code'),
        ),
    ]
