# Generated by Django 4.2.7 on 2024-05-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0012_payment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profit_increment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
