# Generated by Django 4.2.7 on 2025-03-06 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0016_online_trading'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='online_trading',
            new_name='Online_Training',
        ),
    ]
